---
Name: ecommerce_tax
Before: 'mysite/*'
After: 'framework/*','cms/*','ecommerce/*'
---

OrderModifier_Descriptor:
  extensions:
    - GSTTaxDecorator

Product:
  extensions:
    - GSTTaxDecorator

StoreAdmin:
  managed_models:
    - GSTTaxModifierOptions

---
Only:
  classexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - GSTTaxDecorator



