---
Name: ecommerce_tax
Before: 'app/*'
After: 'framework/*','cms/*','ecommerce/*'
---
OrderModifier_Descriptor:
  extensions:
    - Sunnysideup\EcommerceTax\Decorator\GSTTaxDecorator
Sunnysideup\Ecommerce\Pages\Product:
  extensions:
    - Sunnysideup\EcommerceTax\Decorator\GSTTaxDecorator
Sunnysideup\Ecommerce\Cms\StoreAdmin:
  managed_models:
    - Sunnysideup\EcommerceTax\Model\GSTTaxModifierOptions
---
Only:
  classexists: 'ProductVariation'
---
ProductVariation:
  extensions:
    - Sunnysideup\EcommerceTax\Decorator\GSTTaxDecorator
